/**
 * The list of models the app can run.
 *
 * `models/manifest.json` is generated by the Vite plugin in
 * `plugins/models-manifest.ts`, which simply scans `public/models` for `.onnx`
 * files — dropping a freshly exported model into that folder is all it takes
 * for it to show up in the dropdown.
 */

export interface ModelEntry {
  /** Checkpoint stem, unique within the folder. */
  id: string;
  /** Model folder name under `models/`, e.g. "gpt_small". */
  model: string;
  /** File name of the .onnx, relative to the models folder. */
  file: string;
  contextSize: number;
  sizeBytes: number;
  step: number | null;
  params: number | null;
  vocabSize: number | null;
  exportedAt: string | null;
  /** True when a `<checkpoint>.json` sidecar was found next to the .onnx. */
  hasMetadata: boolean;
}

export interface Manifest {
  generatedAt: string;
  models: ModelEntry[];
}

const BASE = import.meta.env.BASE_URL;

export const MODELS_URL = `${BASE}models/`;
export const TOKENIZER_URL = `${MODELS_URL}tokenizer.json`;

export function modelUrl(entry: ModelEntry): string {
  return `${MODELS_URL}${entry.file}`;
}

export async function loadManifest(): Promise<Manifest> {
  const response = await fetch(`${MODELS_URL}manifest.json`);
  if (!response.ok) {
    throw new Error(`Failed to load the model manifest: ${response.status}`);
  }
  return (await response.json()) as Manifest;
}

/** Human-readable label for the dropdown. */
export function describe(entry: ModelEntry): string {
  const parts = [entry.model];
  if (entry.step !== null) parts.push(`step ${entry.step.toLocaleString()}`);
  parts.push(`${(entry.sizeBytes / 1e6).toFixed(1)} MB`);
  return parts.join(" · ");
}
