/**
 * Browser-side port of `tinyfacts_learn.tokenizers.WordTokenizer`.
 *
 * The vocabulary itself is not rebuilt here — it is loaded from the
 * `tokenizer.json` produced by `main.py export`, so the ids the browser
 * produces are by construction the ids the model was trained on. The
 * tokenize/detokenize *logic* is mirrored from the Python class and must stay
 * in step with it; `webapp/test/tokenizer.test.ts` checks it against cases
 * generated by the Python tokenizer.
 */

export interface TokenizerData {
  /** Token strings, indexed by token id. */
  tokens: string[];
  /** Surface form -> the token ids it expands to (a tag id may precede the base). */
  wordTokens: Record<string, number[]>;
  /** "TAG|base" (tag empty for base forms) -> surface form, for detokenizing. */
  formLookup: Record<string, string>;
  tags: string[];
  specials: string;
  digits: string[];
  unkId: number;
  upcId: number | null;
  ignoreCase: boolean;
  vocabSize: number;
}

/** A stretch of the input text and the tokens it produced. */
export interface Segment {
  start: number;
  end: number;
  text: string;
  ids: number[];
  /** True when this stretch tokenized to `<UNK>` — the model cannot read it. */
  unknown: boolean;
}

const WORD_RE = /^[a-zA-Z][a-z]*/;
const SPACE_RE = /^\s+/;
const KEY_SEP = "|";

export class WordTokenizer {
  private readonly data: TokenizerData;
  private readonly tagSet: Set<string>;
  private readonly digitSet: Set<string>;
  private readonly tokenToId: Map<string, number>;

  constructor(data: TokenizerData) {
    this.data = data;
    this.tagSet = new Set(data.tags);
    this.digitSet = new Set(data.digits);
    this.tokenToId = new Map(data.tokens.map((token, id) => [token, id]));
  }

  static async load(url: string): Promise<WordTokenizer> {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`Failed to load tokenizer from ${url}: ${response.status}`);
    }
    return new WordTokenizer((await response.json()) as TokenizerData);
  }

  get vocabSize(): number {
    return this.data.vocabSize;
  }

  tokenText(id: number): string {
    return this.data.tokens[id] ?? "<UNK>";
  }

  /** Token ids for a piece of text, mirroring WordTokenizer.tokenize. */
  tokenize(text: string): number[] {
    return this.segment(text).flatMap((s) => s.ids);
  }

  /**
   * Tokenize while keeping track of which characters produced which tokens.
   *
   * Every character of the input lands in exactly one segment (whitespace
   * included, as an empty-id segment), so concatenating `segment.text` in order
   * reproduces the input — which is what lets the UI overlay highlights on the
   * raw text.
   */
  segment(text: string): Segment[] {
    const { unkId, upcId, ignoreCase } = this.data;
    const segments: Segment[] = [];
    let cursor = 0;

    while (cursor < text.length) {
      const rest = text.slice(cursor);
      const wordMatch = WORD_RE.exec(rest);

      if (wordMatch) {
        const raw = wordMatch[0];
        const ids: number[] = [];
        let word = raw;
        if (/[A-Z]/.test(word[0])) {
          if (!ignoreCase && upcId !== null) {
            ids.push(upcId);
          }
          word = word.toLowerCase();
        }
        const wordIds = this.data.wordTokens[word];
        if (wordIds) {
          ids.push(...wordIds);
        } else {
          ids.push(unkId);
        }
        segments.push({
          start: cursor,
          end: cursor + raw.length,
          text: raw,
          ids,
          unknown: wordIds === undefined,
        });
        cursor += raw.length;
        continue;
      }

      const spaceMatch = SPACE_RE.exec(rest);
      if (spaceMatch) {
        // Whitespace carries no tokens, but must still be rendered.
        segments.push({
          start: cursor,
          end: cursor + spaceMatch[0].length,
          text: spaceMatch[0],
          ids: [],
          unknown: false,
        });
        cursor += spaceMatch[0].length;
        continue;
      }

      // A single digit or punctuation character — or something out of vocabulary.
      const char = rest[0];
      const id = this.idOf(char);
      segments.push({
        start: cursor,
        end: cursor + 1,
        text: char,
        ids: [id],
        unknown: id === unkId,
      });
      cursor += 1;
    }

    return segments;
  }

  /** Text for a list of token ids, mirroring WordTokenizer.detokenize. */
  detokenize(ids: number[]): string {
    let text = "";
    let queuedTag: string | null = null;
    let queuedUpper = false;

    for (const id of ids) {
      let token = this.tokenText(id);

      if (this.tagSet.has(token)) {
        queuedTag = token;
        continue;
      }
      if (token === "<UPC>") {
        queuedUpper = true;
        continue;
      }

      if (queuedTag) {
        const tag = queuedTag.slice(1, -1);
        token = this.data.formLookup[`${tag}${KEY_SEP}${token}`] ?? "<UNK>";
        queuedTag = null;
      }

      if (queuedUpper) {
        token = token.toUpperCase();
        queuedUpper = false;
      }

      if (this.data.specials.includes(token)) {
        text = text.trim(); // no space before punctuation
      }

      if (this.digitSet.has(token) && text.length > 1 && this.digitSet.has(text[text.length - 2])) {
        text = text.trim(); // digits of one number run together
      }

      text += token + " ";
    }

    return text.trim();
  }

  private idOf(token: string): number {
    return this.tokenToId.get(token) ?? this.data.unkId;
  }
}
