[project]
name = "tinyfacts-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.18.4",
    "matplotlib>=3.10.8",
    "miniml-jax>=0.6.0",
    "numpy>=2.4.0",
    "scipy>=1.16.3",
    "tinyfacts-gen",
    "torch>=2.10.0",
    "typer>=0.21.1",
]

[tool.uv.workspace]
members = [
    "tinyfacts-gen",
]

[tool.uv.sources]
tinyfacts-gen = { workspace = true }

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
