import { describe, expect, it } from "vitest";

import { WordTokenizer, type TokenizerData } from "../src/tokenizer";
import cases from "./fixtures/cases.json";
import tokenizerData from "./fixtures/tokenizer.json";

/**
 * The fixtures are generated by `python tests/test_webapp_fixtures.py` straight
 * from the Python `WordTokenizer`, and a pytest fails if they go stale. So
 * matching them here is a real check that the browser feeds the model the same
 * ids the model was trained on.
 */
const tokenizer = new WordTokenizer(tokenizerData as unknown as TokenizerData);

describe("WordTokenizer", () => {
  it("exposes the trained vocabulary size", () => {
    expect(tokenizer.vocabSize).toBe((tokenizerData as { vocabSize: number }).vocabSize);
  });

  describe.each(cases)("$text", (testCase) => {
    it("tokenizes exactly as the Python tokenizer does", () => {
      expect(tokenizer.tokenize(testCase.text)).toEqual(testCase.ids);
    });

    it("detokenizes exactly as the Python tokenizer does", () => {
      expect(tokenizer.detokenize(testCase.ids)).toBe(testCase.detokenized);
    });

    it("covers every character of the input with a segment", () => {
      const segments = tokenizer.segment(testCase.text);
      expect(segments.map((s) => s.text).join("")).toBe(testCase.text);
      expect(segments.flatMap((s) => s.ids)).toEqual(testCase.ids);

      let cursor = 0;
      for (const segment of segments) {
        expect(segment.start).toBe(cursor);
        expect(segment.end).toBe(cursor + segment.text.length);
        cursor = segment.end;
      }
    });
  });

  it("flags out-of-vocabulary words and only those", () => {
    const segments = tokenizer.segment("quantum entanglement of xylophones");
    const unknown = segments.filter((s) => s.unknown).map((s) => s.text);
    expect(unknown).toEqual(["quantum", "entanglement", "xylophones"]);
  });

  it("flags an unknown word in the middle of a known sentence", () => {
    const segments = tokenizer.segment("the sun is a giraffe");
    expect(segments.filter((s) => s.unknown).map((s) => s.text)).toEqual(["giraffe"]);
  });

  it("does not flag punctuation or digits", () => {
    const segments = tokenizer.segment("there are 42 things, here.");
    expect(segments.filter((s) => s.unknown)).toEqual([]);
  });

  it("flags a character outside the vocabulary", () => {
    const segments = tokenizer.segment("the sun ~ hot");
    expect(segments.filter((s) => s.unknown).map((s) => s.text)).toEqual(["~"]);
  });

  it("is case-insensitive, like the trained tokenizer", () => {
    expect(tokenizer.tokenize("The Sun")).toEqual(tokenizer.tokenize("the sun"));
  });
});
